using System;

namespace Nexus.Core.Entities
{
    /// <summary>
    /// Represents the immutable output prediction/evaluation generated by the neural runtime model.
    /// </summary>
    public class EvaluationResult
    {
        public double BuyConfidence { get; }
        public double SellConfidence { get; }
        public double WaitConfidence { get; }
        public double ExpectedMovement { get; }
        public double RiskScore { get; }
        public double Confidence { get; }
        public string MarketRegime { get; }

        public EvaluationResult(
            double buyConfidence,
            double sellConfidence,
            double waitConfidence,
            double expectedMovement,
            double riskScore,
            double confidence,
            string marketRegime)
        {
            BuyConfidence = buyConfidence;
            SellConfidence = sellConfidence;
            WaitConfidence = waitConfidence;
            ExpectedMovement = expectedMovement;
            RiskScore = riskScore;
            Confidence = confidence;
            MarketRegime = marketRegime ?? "Unknown";
        }

        public override string ToString()
        {
            return $"Buy={BuyConfidence:P0}, Sell={SellConfidence:P0}, Wait={WaitConfidence:P0}, ExpectedMov={ExpectedMovement:F5}, Risk={RiskScore:F2}, Regime={MarketRegime}";
        }
    }
}
