namespace Nexus.Core.Entities
{
    public enum TimeframeInterval
    {
        M1,
        M5,
        M15,
        M30,
        H1,
        H4,
        D1
    }

    public enum TrendDirection
    {
        BULLISH,
        BEARISH,
        NEUTRAL
    }

    /// <summary>
    /// Represents a discrete analytical evaluation signal generated by an independent timeframe-specific pipeline.
    /// </summary>
    public sealed class MultiTimeframeSignal
    {
        public TimeframeInterval Timeframe { get; }
        public TrendDirection Trend { get; }
        public double Strength { get; } // 0.0 to 1.0
        public double Volatility { get; }
        public double Momentum { get; }
        public double Confidence { get; } // 0.0 to 1.0
        public DateTime TimestampUtc { get; }

        public MultiTimeframeSignal(
            TimeframeInterval timeframe,
            TrendDirection trend,
            double strength,
            double volatility,
            double momentum,
            double confidence,
            DateTime timestampUtc)
        {
            Timeframe = timeframe;
            Trend = trend;
            Strength = Math.Clamp(strength, 0.0, 1.0);
            Volatility = volatility;
            Momentum = momentum;
            Confidence = Math.Clamp(confidence, 0.0, 1.0);
            TimestampUtc = timestampUtc;
        }
    }
}
