using Nexus.Core.Enums;
using Nexus.Core.ValueObjects;

namespace Nexus.Core.Entities
{
    /// <summary>
    /// Represents the complete institutional-grade trade action matrix executed by the AI Quant Engine.
    /// Preserves original base execution properties (BUY, SELL, WAIT, CLOSE, REDUCE, ADD) for full 
    /// backward compatibility while extending to support advanced conditional pending orders.
    /// </summary>
    /// <remarks>
    /// Reference Files:
    /// - Utilized in: src/Nexus.Core/Entities/TradeDecision.cs
    /// - Consumed by: src/Nexus.Application/AI/Decision/DecisionFusionEngine.cs
    /// - Evaluated in: src/Nexus.Application/AI/Decision/AiTradingOrchestrator.cs
    /// </remarks>
    public enum DecisionAction
    {
        #region Base Core Execution Actions (Preserved for Backward Compatibility)
        /// <summary>
        /// Instantly executes a market BUY order with volume-aware sizing on the broker server.
        /// </summary>
        BUY = 0,

        /// <summary>
        /// Instantly executes a market SELL order with volume-aware sizing on the broker server.
        /// </summary>
        SELL = 1,

        /// <summary>
        /// Indicates a non-execution or standby state. No action or new exposure is taken on this tick.
        /// </summary>
        WAIT = 2,

        /// <summary>
        /// Triggers instant liquidation (full closure) of open positions on the active symbol.
        /// </summary>
        CLOSE = 3,

        /// <summary>
        /// Partially closes or reduces the exposure of an active position to secure profits or cut risk.
        /// </summary>
        REDUCE = 4,

        /// <summary>
        /// Adds volume or scales into an active, profitable position based on trend confirmation.
        /// </summary>
        ADD = 5,
        #endregion

        #region Extended Pending Limit Actions (Scalping Additions)
        /// <summary>
        /// Placed at a discount price level below current market price. Activated upon favorable price retracements.
        /// </summary>
        BUY_LIMIT = 6,

        /// <summary>
        /// Placed at a premium price level above current market price. Activated upon favorable price retracements.
        /// </summary>
        SELL_LIMIT = 7,
        #endregion

        #region Extended Pending Stop Breakout Actions (Scalping Additions)
        /// <summary>
        /// Placed above current market price. Activated when upward price breakout momentum triggers.
        /// </summary>
        BUY_STOP = 8,

        /// <summary>
        /// Placed below current market price. Activated when downward price breakout momentum triggers.
        /// </summary>
        SELL_STOP = 9
        #endregion
    }

    /// <summary>
    /// Represents the ultimate high-precision trade decision payload generated by the Decision Engine Core.
    /// Integrates newly-defined Value Objects and expanded Decision Action Enums while maintaining 
    /// absolute backward compatibility with legacy execution gateways.
    /// </summary>
    /// <remarks>
    /// Reference Files:
    /// - Output of: src/Nexus.Application/AI/Decision/DecisionFusionEngine.cs
    /// - Evaluated in: src/Nexus.Application/AI/Decision/AiTradingOrchestrator.cs
    /// - Target Enums: src/Nexus.Core/Enums/DecisionAction.cs
    /// </remarks>
    public class TradeDecision
    {
        #region Core Backing Fields & Properties
        /// <summary>
        /// The precise decision action resolved by the AI Core (including conditional Limit/Stop orders).
        /// </summary>
        public DecisionAction Action { get; }

        /// <summary>
        /// The targeted lot size / volume calculated dynamically by the position sizer.
        /// </summary>
        public double TargetVolume { get; }

        /// <summary>
        /// Comprehensive, audit-ready string detailing the technical or neural reasoning behind this decision.
        /// </summary>
        public string Reason { get; }

        /// <summary>
        /// Exact timestamp when the decision was fused and signed by the quantitative engine.
        /// </summary>
        public DateTime TimestampUtc { get; }
        #endregion

        #region Value Object Projections (Backward Compatibility Layers)
        /// <summary>
        /// Adapts the rich AI <see cref="DecisionAction"/> to the traditional legacy <see cref="TradeAction"/>
        /// for consumption by downstream execution systems that do not support pending orders natively.
        /// </summary>
        public TradeAction TradeAction => Action switch
        {
            DecisionAction.BUY => TradeAction.BUY,
            DecisionAction.SELL => TradeAction.SELL,
            DecisionAction.WAIT => TradeAction.WAIT,
            DecisionAction.CLOSE => TradeAction.CLOSE,

            // Scalping Extensions Mapping: Direct pending orders to their dominant market direction
            DecisionAction.BUY_LIMIT => TradeAction.BUY,
            DecisionAction.SELL_LIMIT => TradeAction.SELL,
            DecisionAction.BUY_STOP => TradeAction.BUY,
            DecisionAction.SELL_STOP => TradeAction.SELL,

            // Default protection fallback
            _ => TradeAction.MODIFY
        };

        /// <summary>
        /// Compiles the raw float volume into a domain-validated <see cref="Volume"/> Value Object.
        /// </summary>
        public Volume VolumeObj => new Volume(TargetVolume);
        #endregion

        #region Constructors
        /// <summary>
        /// Primary constructor initializing a new validated decision record from the AI Fusion engine.
        /// </summary>
        /// <param name="action">The advanced decision action code.</param>
        /// <param name="targetVolume">The raw double lot size resolved by the risk controllers.</param>
        /// <param name="reason">The descriptive audit reasons explaining the decision.</param>
        /// <param name="timestampUtc">The UTC timestamp of the creation event.</param>
        public TradeDecision(DecisionAction action, double targetVolume, string reason, DateTime timestampUtc)
        {
            Action = action;
            TargetVolume = targetVolume;
            Reason = reason ?? string.Empty;
            TimestampUtc = timestampUtc;
        }

        /// <summary>
        /// Legacy compatibility constructor allowing creation of decisions from classic TradeAction and Volume Value Objects.
        /// Maps classic parameters to their respective advanced AI counterparts safely.
        /// </summary>
        /// <param name="action">The traditional trade execution action.</param>
        /// <param name="targetVolume">The domain-validated Volume value object.</param>
        /// <param name="reason">The reasoning text behind this execution.</param>
        /// <param name="timestampUtc">The UTC timestamp of creation.</param>
        public TradeDecision(TradeAction action, Volume targetVolume, string reason, DateTime timestampUtc)
            : this(
                  action switch
                  {
                      TradeAction.BUY => DecisionAction.BUY,
                      TradeAction.SELL => DecisionAction.SELL,
                      TradeAction.WAIT => DecisionAction.WAIT,
                      TradeAction.CLOSE => DecisionAction.CLOSE,
                      _ => DecisionAction.REDUCE // Safe default mapping
                  },
                  targetVolume != null ? targetVolume.Value : 0.01,
                  reason,
                  timestampUtc)
        {
        }
        #endregion

        #region Diagnostic Utilities
        /// <summary>
        /// Translates the full decision state into a clean monospace console log format.
        /// </summary>
        /// <returns>A formatted diagnostics string.</returns>
        public override string ToString()
        {
            return $"[{TimestampUtc:HH:mm:ss}] Action: {Action}, Volume: {TargetVolume:F2}, Reason: {Reason}";
        }
        #endregion
    }
}