using Nexus.Core.Enums;
using Nexus.Core.ValueObjects;

namespace Nexus.Core.Entities
{
    public enum DecisionAction
    {
        BUY,
        SELL,
        WAIT,
        CLOSE,
        REDUCE,
        ADD
    }

    /// <summary>
    /// Represents the ultimate decision payload generated by the Decision Engine.
    /// Integrates newly-defined Value Objects and Enums while keeping full backward compatibility.
    /// </summary>
    public class TradeDecision
    {
        public DecisionAction Action { get; }
        public double TargetVolume { get; }
        public string Reason { get; }
        public DateTime TimestampUtc { get; }

        #region Value Object properties

        public TradeAction TradeAction => Action switch
        {
            DecisionAction.BUY => TradeAction.BUY,
            DecisionAction.SELL => TradeAction.SELL,
            DecisionAction.WAIT => TradeAction.WAIT,
            DecisionAction.CLOSE => TradeAction.CLOSE,
            _ => TradeAction.MODIFY
        };

        public Volume VolumeObj => new Volume(TargetVolume);

        #endregion

        public TradeDecision(DecisionAction action, double targetVolume, string reason, DateTime timestampUtc)
        {
            Action = action;
            TargetVolume = targetVolume;
            Reason = reason ?? string.Empty;
            TimestampUtc = timestampUtc;
        }

        public TradeDecision(TradeAction action, Volume targetVolume, string reason, DateTime timestampUtc)
            : this(
                  action switch
                  {
                      TradeAction.BUY => DecisionAction.BUY,
                      TradeAction.SELL => DecisionAction.SELL,
                      TradeAction.WAIT => DecisionAction.WAIT,
                      TradeAction.CLOSE => DecisionAction.CLOSE,
                      _ => DecisionAction.REDUCE
                  },
                  targetVolume.Value,
                  reason,
                  timestampUtc)
        {
        }

        public override string ToString()
        {
            return $"[{TimestampUtc:HH:mm:ss}] Action: {Action}, Volume: {TargetVolume:F2}, Reason: {Reason}";
        }
    }
}
