using System;

namespace Nexus.Core.Entities
{
    public enum DecisionAction
    {
        BUY,
        SELL,
        WAIT,
        CLOSE,
        REDUCE,
        ADD
    }

    /// <summary>
    /// Represents the ultimate decision payload generated by the Decision Engine.
    /// </summary>
    public class TradeDecision
    {
        public DecisionAction Action { get; }
        public double TargetVolume { get; }
        public string Reason { get; }
        public DateTime TimestampUtc { get; }

        public TradeDecision(DecisionAction action, double targetVolume, string reason, DateTime timestampUtc)
        {
            Action = action;
            TargetVolume = targetVolume;
            Reason = reason ?? string.Empty;
            TimestampUtc = timestampUtc;
        }

        public override string ToString()
        {
            return $"[{TimestampUtc:HH:mm:ss}] Action: {Action}, Volume: {TargetVolume:F2}, Reason: {Reason}";
        }
    }
}
