using Nexus.Core.Entities;

namespace Nexus.DecisionEngine
{
    /// <summary>
    /// Represents the ultimate decision payload generated by the Decision Engine.
    /// Includes the selected action, confidence level, evidence, rejected alternatives,
    /// risk summary, expected outcomes, and whether it is ready for execution.
    /// </summary>
    public sealed class DecisionPackage
    {
        public DecisionAction SelectedAction { get; }
        public double Confidence { get; } // 0.0 to 1.0
        public string Evidence { get; }
        public Dictionary<DecisionAction, double> AlternativeDecisions { get; }
        public string RiskSummary { get; }
        public string ExpectedOutcome { get; }
        public bool IsExecutionReady { get; }
        public DateTime TimestampUtc { get; }

        public DecisionPackage(
            DecisionAction selectedAction,
            double confidence,
            string evidence,
            Dictionary<DecisionAction, double> alternativeDecisions,
            string riskSummary,
            string expectedOutcome,
            bool isExecutionReady)
        {
            SelectedAction = selectedAction;
            Confidence = confidence;
            Evidence = evidence ?? string.Empty;
            AlternativeDecisions = alternativeDecisions ?? new Dictionary<DecisionAction, double>();
            RiskSummary = riskSummary ?? string.Empty;
            ExpectedOutcome = expectedOutcome ?? string.Empty;
            IsExecutionReady = isExecutionReady;
            TimestampUtc = DateTime.UtcNow;
        }

        public override string ToString()
        {
            return $"[{TimestampUtc:HH:mm:ss}] Selected: {SelectedAction}, Confidence: {Confidence:P0}, Ready: {IsExecutionReady}";
        }
    }
}
