// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
namespace Nexus_AI
{
    public partial class NexuSModelV1
    {
        /// <summary>
        /// model input class for NexuSModelV1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"time")]
            public string Time { get; set; } = default!;

            [LoadColumn(1)]
            [ColumnName(@"open")]
            public float Open { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"prev_high")]
            public float Prev_high { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"prev_low")]
            public float Prev_low { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"prev_close")]
            public float Prev_close { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"atr_proxy_14")]
            public float Atr_proxy_14 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"range_mean_20")]
            public float Range_mean_20 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"volume_mean_20")]
            public float Volume_mean_20 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"volume_ratio")]
            public float Volume_ratio { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"swing_high_20")]
            public float Swing_high_20 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"swing_low_20")]
            public float Swing_low_20 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"break_high_20")]
            public float Break_high_20 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"break_low_20")]
            public float Break_low_20 { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"higher_high")]
            public float Higher_high { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"lower_low")]
            public float Lower_low { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"RSI_14")]
            public float RSI_14 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"MACD_Line")]
            public float MACD_Line { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"MACD_Signal")]
            public float MACD_Signal { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"MACD_Hist")]
            public float MACD_Hist { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"BB_Upper")]
            public float BB_Upper { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"BB_Lower")]
            public float BB_Lower { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"BB_Width")]
            public float BB_Width { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"BB_Position")]
            public float BB_Position { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"EMA_9")]
            public float EMA_9 { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"EMA_21")]
            public float EMA_21 { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"EMA_50")]
            public float EMA_50 { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"ROC_5")]
            public float ROC_5 { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"dist_to_swing_high")]
            public float Dist_to_swing_high { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"dist_to_swing_low")]
            public float Dist_to_swing_low { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"volatility_ratio")]
            public float Volatility_ratio { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"prev_close_lag_1")]
            public float Prev_close_lag_1 { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"prev_close_lag_2")]
            public float Prev_close_lag_2 { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"prev_close_lag_3")]
            public float Prev_close_lag_3 { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"atr_proxy_14_lag_1")]
            public float Atr_proxy_14_lag_1 { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"atr_proxy_14_lag_2")]
            public float Atr_proxy_14_lag_2 { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"atr_proxy_14_lag_3")]
            public float Atr_proxy_14_lag_3 { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"volume_ratio_lag_1")]
            public float Volume_ratio_lag_1 { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"volume_ratio_lag_2")]
            public float Volume_ratio_lag_2 { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"volume_ratio_lag_3")]
            public float Volume_ratio_lag_3 { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"RSI_14_lag_1")]
            public float RSI_14_lag_1 { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"RSI_14_lag_2")]
            public float RSI_14_lag_2 { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"RSI_14_lag_3")]
            public float RSI_14_lag_3 { get; set; }

            [LoadColumn(43)]
            [ColumnName(@"MACD_Hist_lag_1")]
            public float MACD_Hist_lag_1 { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"MACD_Hist_lag_2")]
            public float MACD_Hist_lag_2 { get; set; }

            [LoadColumn(45)]
            [ColumnName(@"MACD_Hist_lag_3")]
            public float MACD_Hist_lag_3 { get; set; }

            [LoadColumn(46)]
            [ColumnName(@"hour_sin")]
            public float Hour_sin { get; set; }

            [LoadColumn(47)]
            [ColumnName(@"hour_cos")]
            public float Hour_cos { get; set; }

            [LoadColumn(48)]
            [ColumnName(@"day_sin")]
            public float Day_sin { get; set; }

            [LoadColumn(49)]
            [ColumnName(@"day_cos")]
            public float Day_cos { get; set; }

            [LoadColumn(50)]
            [ColumnName(@"target_next_bullish")]
            public float Target_next_bullish { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for NexuSModelV1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"time")]
            public string Time { get; set; } = default!;

            [ColumnName(@"open")]
            public float Open { get; set; }

            [ColumnName(@"prev_high")]
            public float Prev_high { get; set; }

            [ColumnName(@"prev_low")]
            public float Prev_low { get; set; }

            [ColumnName(@"prev_close")]
            public float Prev_close { get; set; }

            [ColumnName(@"atr_proxy_14")]
            public float Atr_proxy_14 { get; set; }

            [ColumnName(@"range_mean_20")]
            public float Range_mean_20 { get; set; }

            [ColumnName(@"volume_mean_20")]
            public float Volume_mean_20 { get; set; }

            [ColumnName(@"volume_ratio")]
            public float Volume_ratio { get; set; }

            [ColumnName(@"swing_high_20")]
            public float Swing_high_20 { get; set; }

            [ColumnName(@"swing_low_20")]
            public float Swing_low_20 { get; set; }

            [ColumnName(@"break_high_20")]
            public float Break_high_20 { get; set; }

            [ColumnName(@"break_low_20")]
            public float Break_low_20 { get; set; }

            [ColumnName(@"higher_high")]
            public float Higher_high { get; set; }

            [ColumnName(@"lower_low")]
            public float Lower_low { get; set; }

            [ColumnName(@"RSI_14")]
            public float RSI_14 { get; set; }

            [ColumnName(@"MACD_Line")]
            public float MACD_Line { get; set; }

            [ColumnName(@"MACD_Signal")]
            public float MACD_Signal { get; set; }

            [ColumnName(@"MACD_Hist")]
            public float MACD_Hist { get; set; }

            [ColumnName(@"BB_Upper")]
            public float BB_Upper { get; set; }

            [ColumnName(@"BB_Lower")]
            public float BB_Lower { get; set; }

            [ColumnName(@"BB_Width")]
            public float BB_Width { get; set; }

            [ColumnName(@"BB_Position")]
            public float BB_Position { get; set; }

            [ColumnName(@"EMA_9")]
            public float EMA_9 { get; set; }

            [ColumnName(@"EMA_21")]
            public float EMA_21 { get; set; }

            [ColumnName(@"EMA_50")]
            public float EMA_50 { get; set; }

            [ColumnName(@"ROC_5")]
            public float ROC_5 { get; set; }

            [ColumnName(@"dist_to_swing_high")]
            public float Dist_to_swing_high { get; set; }

            [ColumnName(@"dist_to_swing_low")]
            public float Dist_to_swing_low { get; set; }

            [ColumnName(@"volatility_ratio")]
            public float Volatility_ratio { get; set; }

            [ColumnName(@"prev_close_lag_1")]
            public float Prev_close_lag_1 { get; set; }

            [ColumnName(@"prev_close_lag_2")]
            public float Prev_close_lag_2 { get; set; }

            [ColumnName(@"prev_close_lag_3")]
            public float Prev_close_lag_3 { get; set; }

            [ColumnName(@"atr_proxy_14_lag_1")]
            public float Atr_proxy_14_lag_1 { get; set; }

            [ColumnName(@"atr_proxy_14_lag_2")]
            public float Atr_proxy_14_lag_2 { get; set; }

            [ColumnName(@"atr_proxy_14_lag_3")]
            public float Atr_proxy_14_lag_3 { get; set; }

            [ColumnName(@"volume_ratio_lag_1")]
            public float Volume_ratio_lag_1 { get; set; }

            [ColumnName(@"volume_ratio_lag_2")]
            public float Volume_ratio_lag_2 { get; set; }

            [ColumnName(@"volume_ratio_lag_3")]
            public float Volume_ratio_lag_3 { get; set; }

            [ColumnName(@"RSI_14_lag_1")]
            public float RSI_14_lag_1 { get; set; }

            [ColumnName(@"RSI_14_lag_2")]
            public float RSI_14_lag_2 { get; set; }

            [ColumnName(@"RSI_14_lag_3")]
            public float RSI_14_lag_3 { get; set; }

            [ColumnName(@"MACD_Hist_lag_1")]
            public float MACD_Hist_lag_1 { get; set; }

            [ColumnName(@"MACD_Hist_lag_2")]
            public float MACD_Hist_lag_2 { get; set; }

            [ColumnName(@"MACD_Hist_lag_3")]
            public float MACD_Hist_lag_3 { get; set; }

            [ColumnName(@"hour_sin")]
            public float Hour_sin { get; set; }

            [ColumnName(@"hour_cos")]
            public float Hour_cos { get; set; }

            [ColumnName(@"day_sin")]
            public float Day_sin { get; set; }

            [ColumnName(@"day_cos")]
            public float Day_cos { get; set; }

            [ColumnName(@"target_next_bullish")]
            public uint Target_next_bullish { get; set; }

            [ColumnName(@"Features")]

            public float[] Features { get; set; } = default!;

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; } = default!;

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("NexuSModelV1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("target_next_bullish");
            if (labelColumn == null)
            {
                throw new Exception("target_next_bullish column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
