// ============================================================================
// PROJECT: NEXUS QUANTITATIVE TRADING PLATFORM
// LAYER:   CORE LAYER (Domain Entities)
// FILE:    ProbabilisticPrediction.cs
// REFERENCED BY:
//   - src/Nexus.Core/AI/Interfaces/IInferenceEngine.cs
// ============================================================================

namespace Nexus.Core.AI.Entities
{
    /// <summary>
    /// Represents the rich multi-horizon probabilistic forecast generated by the Temporal Fusion Transformer.
    /// Combines categorical trading action probabilities with continuous expected values.
    /// </summary>
    public sealed class ProbabilisticPrediction
    {
        /// <summary>
        /// Calculated probability [0.0 to 1.0] for initiating buy orders.
        /// </summary>
        public double BuyProbability { get; }

        /// <summary>
        /// Calculated probability [0.0 to 1.0] for initiating sell orders.
        /// </summary>
        public double SellProbability { get; }

        /// <summary>
        /// Calculated probability [0.0 to 1.0] for remaining flat (no-trade).
        /// </summary>
        public double NoTradeProbability { get; }

        /// <summary>
        /// Confidence level [0.0 to 1.0] of the attention layers regarding this prediction.
        /// </summary>
        public double ConfidenceScore { get; }

        /// <summary>
        /// Mathematical expected value of return (profit) in pips.
        /// </summary>
        public double ExpectedReturn { get; }

        /// <summary>
        /// Mathematical expected value of downside risk in pips.
        /// </summary>
        public double ExpectedRisk { get; }

        /// <summary>
        /// Maximum adverse excursion (MAdE) projected during trade duration.
        /// </summary>
        public double ExpectedDrawdown { get; }

        /// <summary>
        /// Projected trade duration in minutes.
        /// </summary>
        public double ExpectedHoldingTimeMinutes { get; }

        /// <summary>
        /// Cosine similarity index of current state compared to successful historical experiences.
        /// </summary>
        public double HistoricalSimilarityScore { get; }

        /// <summary>
        /// Total mathematical uncertainty index of the forecasting quantiles.
        /// </summary>
        public double PredictionUncertainty { get; }

        /// <summary>
        /// The classified market state structure (e.g. Volatile-Range, Trending-Bullish).
        /// </summary>
        public string MarketRegimeClassification { get; }

        /// <summary>
        /// UTC timestamp of prediction generation.
        /// </summary>
        public DateTime GeneratedAtUtc { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProbabilisticPrediction"/> class.
        /// </summary>
        public ProbabilisticPrediction(
            double buyProbability,
            double sellProbability,
            double noTradeProbability,
            double confidenceScore,
            double expectedReturn,
            double expectedRisk,
            double expectedDrawdown,
            double expectedHoldingTimeMinutes,
            double historicalSimilarityScore,
            double predictionUncertainty,
            string marketRegimeClassification,
            DateTime generatedAtUtc)
        {
            BuyProbability = buyProbability;
            SellProbability = sellProbability;
            NoTradeProbability = noTradeProbability;
            ConfidenceScore = confidenceScore;
            ExpectedReturn = expectedReturn;
            ExpectedRisk = expectedRisk;
            ExpectedDrawdown = expectedDrawdown;
            ExpectedHoldingTimeMinutes = expectedHoldingTimeMinutes;
            HistoricalSimilarityScore = historicalSimilarityScore;
            PredictionUncertainty = predictionUncertainty;
            MarketRegimeClassification = marketRegimeClassification ?? "Unknown";
            GeneratedAtUtc = generatedAtUtc;
        }
    }
}